chart = {
    "Area": {
        "alias": [],
        "channel": ["Color", "Position"],
        "def": "An area chart uses series of line segments with overlapped areas to show the change in data in a ordinal dimension.",
        "name": "Area",
        "purpose": ["Comparison", "Trend", "Anomaly"],
        "shape": ["Area"],
    },
    "Bar": {
        "alias": ["Bars"],
        "channel": ["Position", "Color"],
        "dataPres": [
            {"fieldConditions": ["Nominal", "Ordinal"], "maxQty": 2, "minQty": 1},
            {"fieldConditions": ["Interval"], "maxQty": 1, "minQty": 1},
        ],
        "def": "A bar chart uses series of bars to display the value of the dimension. The vertical axis shows the classification dimension and the horizontal axis shows the corresponding value.",
        "name": "Bar",
        "purpose": ["Comparison", "Distribution", "Rank"],
        "shape": ["Bars"],
    },
    "Bullet": {
        "alias": ["Bullet Chart", "Performance Chart"],
        "category": ["Statistic"],
        "channel": ["Position", "Length", "Color"],
        "coord": ["Cartesian2D"],
        "def": "A bullet chart is a variation of a bar graph developed to replace dashboard gauges and meters. It is used primarily to compare a single measure to some pre-defined thresholds or to another measure.",
        "name": "Bullet",
        "purpose": ["Comparison", "Benchmark", "Performance"],
        "shape": ["Bar", "Tick"],
    },
    "Column": {
        "alias": ["Columns"],
        "category": ["Statistic"],
        "channel": ["Position", "Color"],
        "coord": ["Cartesian2D"],
        "def": "A column chart uses series of columns to display the value of the dimension. The horizontal axis shows the classification dimension and the vertical axis shows the corresponding value.",
        "name": "Column",
        "purpose": ["Comparison", "Distribution", "Rank"],
        "shape": ["Bars"],
    },
    "Line": {
        "alias": ["Lines"],
        "category": ["Statistic"],
        "channel": ["Position", "Direction"],
        "coord": ["Cartesian2D"],
        "def": "A line chart uses lines with segments to show changes in data in a ordinal dimension.",
        "name": "Line",
        "purpose": ["Comparison", "Trend", "Anomaly"],
        "shape": ["Lines"],
    },
    "Pie": {
        "alias": ["Circle Chart", "Pie"],
        "channel": ["Angle", "Area", "Color"],
        "coord": ["Polar"],
        "dataPres": [
            {"fieldConditions": ["Nominal", "Ordinal"], "maxQty": 1, "minQty": 1},
            {"fieldConditions": ["Interval"], "maxQty": 1, "minQty": 1},
        ],
        "def": "A pie chart is a chart that the classification and proportion of data are represented by the color and arc length (angle, area) of the sector.",
        "name": "Pie",
        "purpose": ["Comparison", "Composition", "Proportion"],
        "recRate": "Use with Caution",
    },
    "Scatter": {
        "alias": ["Scatter Chart", "Scatterplot"],
        "channel": ["Color", "Position"],
        "def": "A scatter plot is a type of plot or mathematical diagram using Cartesian coordinates to display values for typically two variables for series of data.",
        "name": "Scatter",
        "purpose": ["Comparison", "Distribution", "Anomaly"],
        "shape": ["Scatter"],
    },
}
